<?php

/**
 * PluginAssignClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAssignClaimTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginAssignClaimTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAssignClaim');
    }
}