<?php

/**
 * PluginClaimAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClaimAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginClaimAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginClaimAttachment');
    }
}