<?php

/**
 * PluginExpenseTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginExpenseTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginExpenseTypesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginExpenseTypes');
    }
}