<?php

/**
 * PluginClaimRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClaimRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginClaimRequestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginClaimRequest');
    }
}