<?php

/**
 * PluginExpenseTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginExpenseTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginExpenseTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginExpenseType');
    }
}