<?php

/**
 * PluginClaimEventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClaimEventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginClaimEventsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginClaimEvents');
    }
}