<?php

/**
 * PluginAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAttachment');
    }
}