<?php

/**
 * BaseClaimEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $added_by
 * @property integer $is_deleted
 * @property Doctrine_Collection $ClaimRequest
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method integer             getAddedBy()      Returns the current record's "added_by" value
 * @method integer             getIsDeleted()    Returns the current record's "is_deleted" value
 * @method Doctrine_Collection getClaimRequest() Returns the current record's "ClaimRequest" collection
 * @method ClaimEvent          setId()           Sets the current record's "id" value
 * @method ClaimEvent          setName()         Sets the current record's "name" value
 * @method ClaimEvent          setDescription()  Sets the current record's "description" value
 * @method ClaimEvent          setAddedBy()      Sets the current record's "added_by" value
 * @method ClaimEvent          setIsDeleted()    Sets the current record's "is_deleted" value
 * @method ClaimEvent          setClaimRequest() Sets the current record's "ClaimRequest" collection
 * 
 * @package    orangehrm
 * @subpackage model\claim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_claim_event');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('added_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('is_deleted', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaimRequest', array(
             'local' => 'id',
             'foreign' => 'event_type'));
    }
}