<?php

/**
 * BaseExpense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $expense_type_id
 * @property datetime $date
 * @property string $amount
 * @property string $note
 * @property integer $request_id
 * @property integer $is_deleted
 * @property ExpenseType $ExpenseType
 * @property ClaimRequest $ClaimRequest
 * 
 * @method integer      getId()              Returns the current record's "id" value
 * @method integer      getExpenseTypeId()   Returns the current record's "expense_type_id" value
 * @method datetime     getDate()            Returns the current record's "date" value
 * @method string       getAmount()          Returns the current record's "amount" value
 * @method string       getNote()            Returns the current record's "note" value
 * @method integer      getRequestId()       Returns the current record's "request_id" value
 * @method integer      getIsDeleted()       Returns the current record's "is_deleted" value
 * @method ExpenseType  getExpenseType()     Returns the current record's "ExpenseType" value
 * @method ClaimRequest getClaimRequest()    Returns the current record's "ClaimRequest" value
 * @method Expense      setId()              Sets the current record's "id" value
 * @method Expense      setExpenseTypeId()   Sets the current record's "expense_type_id" value
 * @method Expense      setDate()            Sets the current record's "date" value
 * @method Expense      setAmount()          Sets the current record's "amount" value
 * @method Expense      setNote()            Sets the current record's "note" value
 * @method Expense      setRequestId()       Sets the current record's "request_id" value
 * @method Expense      setIsDeleted()       Sets the current record's "is_deleted" value
 * @method Expense      setExpenseType()     Sets the current record's "ExpenseType" value
 * @method Expense      setClaimRequest()    Sets the current record's "ClaimRequest" value
 * 
 * @package    orangehrm
 * @subpackage model\claim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpense extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_expense');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('expense_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('amount', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('note', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('request_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('is_deleted', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExpenseType', array(
             'local' => 'expense_type_id',
             'foreign' => 'id'));

        $this->hasOne('ClaimRequest', array(
             'local' => 'request_id',
             'foreign' => 'id'));
    }
}