<?php

/**
 * BaseClaimAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $request_id
 * @property integer $attach_id
 * @property integer $size
 * @property string $description
 * @property string $filename
 * @property blob $attachment
 * @property string $file_type
 * @property integer $attached_by
 * @property string $attached_by_name
 * @property timestamp $attached_time
 * @property ClaimRequest $ClaimRequest
 * @property Employee $Employee
 * 
 * @method integer         getRequestId()        Returns the current record's "request_id" value
 * @method integer         getAttachId()         Returns the current record's "attach_id" value
 * @method integer         getSize()             Returns the current record's "size" value
 * @method string          getDescription()      Returns the current record's "description" value
 * @method string          getFilename()         Returns the current record's "filename" value
 * @method blob            getAttachment()       Returns the current record's "attachment" value
 * @method string          getFileType()         Returns the current record's "file_type" value
 * @method integer         getAttachedBy()       Returns the current record's "attached_by" value
 * @method string          getAttachedByName()   Returns the current record's "attached_by_name" value
 * @method timestamp       getAttachedTime()     Returns the current record's "attached_time" value
 * @method ClaimRequest    getClaimRequest()     Returns the current record's "ClaimRequest" value
 * @method Employee        getEmployee()         Returns the current record's "Employee" value
 * @method ClaimAttachment setRequestId()        Sets the current record's "request_id" value
 * @method ClaimAttachment setAttachId()         Sets the current record's "attach_id" value
 * @method ClaimAttachment setSize()             Sets the current record's "size" value
 * @method ClaimAttachment setDescription()      Sets the current record's "description" value
 * @method ClaimAttachment setFilename()         Sets the current record's "filename" value
 * @method ClaimAttachment setAttachment()       Sets the current record's "attachment" value
 * @method ClaimAttachment setFileType()         Sets the current record's "file_type" value
 * @method ClaimAttachment setAttachedBy()       Sets the current record's "attached_by" value
 * @method ClaimAttachment setAttachedByName()   Sets the current record's "attached_by_name" value
 * @method ClaimAttachment setAttachedTime()     Sets the current record's "attached_time" value
 * @method ClaimAttachment setClaimRequest()     Sets the current record's "ClaimRequest" value
 * @method ClaimAttachment setEmployee()         Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\claim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_claim_attachment');
        $this->hasColumn('request_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eattach_id as attach_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('eattach_size as size', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('eattach_desc as description', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('eattach_filename as filename', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('eattach_attachment as attachment', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => 2147483647,
             ));
        $this->hasColumn('eattach_type as file_type', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('attached_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('attached_by_name', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('attached_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimRequest', array(
             'local' => 'request_id',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'attached_by',
             'foreign' => 'emp_number'));
    }
}