<?php

/**
 * BaseAssignClaim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $eventType
 * @property string $currency
 * @property string $description
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getEventType()   Returns the current record's "eventType" value
 * @method string      getCurrency()    Returns the current record's "currency" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method AssignClaim setId()          Sets the current record's "id" value
 * @method AssignClaim setEventType()   Sets the current record's "eventType" value
 * @method AssignClaim setCurrency()    Sets the current record's "currency" value
 * @method AssignClaim setDescription() Sets the current record's "description" value
 * 
 * @package    orangehrm
 * @subpackage model\claim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssignClaim extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_assign_claim');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('eventType', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('currency', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}