<?php

/**
 * BaseClaimRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $emp_number
 * @property integer $added_by
 * @property string $event_type
 * @property string $description
 * @property string $currency
 * @property integer $is_deleted
 * @property ClaimEvent $ClaimEvent
 * @property ExpenseType $ExpenseType
 * @property Employee $Employee
 * @property Doctrine_Collection $Expense
 * @property Doctrine_Collection $ClaimAttachment
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getEmpNumber()       Returns the current record's "emp_number" value
 * @method integer             getAddedBy()         Returns the current record's "added_by" value
 * @method string              getEventType()       Returns the current record's "event_type" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method string              getCurrency()        Returns the current record's "currency" value
 * @method integer             getIsDeleted()       Returns the current record's "is_deleted" value
 * @method ClaimEvent          getClaimEvent()      Returns the current record's "ClaimEvent" value
 * @method ExpenseType         getExpenseType()     Returns the current record's "ExpenseType" value
 * @method Employee            getEmployee()        Returns the current record's "Employee" value
 * @method Doctrine_Collection getExpense()         Returns the current record's "Expense" collection
 * @method Doctrine_Collection getClaimAttachment() Returns the current record's "ClaimAttachment" collection
 * @method ClaimRequest        setId()              Sets the current record's "id" value
 * @method ClaimRequest        setEmpNumber()       Sets the current record's "emp_number" value
 * @method ClaimRequest        setAddedBy()         Sets the current record's "added_by" value
 * @method ClaimRequest        setEventType()       Sets the current record's "event_type" value
 * @method ClaimRequest        setDescription()     Sets the current record's "description" value
 * @method ClaimRequest        setCurrency()        Sets the current record's "currency" value
 * @method ClaimRequest        setIsDeleted()       Sets the current record's "is_deleted" value
 * @method ClaimRequest        setClaimEvent()      Sets the current record's "ClaimEvent" value
 * @method ClaimRequest        setExpenseType()     Sets the current record's "ExpenseType" value
 * @method ClaimRequest        setEmployee()        Sets the current record's "Employee" value
 * @method ClaimRequest        setExpense()         Sets the current record's "Expense" collection
 * @method ClaimRequest        setClaimAttachment() Sets the current record's "ClaimAttachment" collection
 * 
 * @package    orangehrm
 * @subpackage model\claim\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaimRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_claim_request');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('added_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('event_type', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('currency', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('is_deleted', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaimEvent', array(
             'local' => 'event_type',
             'foreign' => 'id'));

        $this->hasOne('ExpenseType', array(
             'local' => 'expense_type',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('Expense', array(
             'local' => 'id',
             'foreign' => 'request_id'));

        $this->hasMany('ClaimAttachment', array(
             'local' => 'id',
             'foreign' => 'request_id'));
    }
}