<?php

/**
 * AssignClaimTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignClaimTable extends PluginAssignClaimTable
{
    /**
     * Returns an instance of this class.
     *
     * @return AssignClaimTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssignClaim');
    }
}