<?php

/**
 * ClaimRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimRequestTable extends PluginClaimRequestTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ClaimRequestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaimRequest');
    }
}