<?php

/**
 * ClaimAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimAttachmentTable extends PluginClaimAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ClaimAttachmentTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaimAttachment');
    }
}