<?php

/**
 * ClaimEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaimEventTable extends PluginClaimEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ClaimEventTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaimEvent');
    }
}