<?php

/**
 * ExpenseTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpenseTypeTable extends PluginExpenseTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return ExpenseTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExpenseType');
    }
}