<?php
/**
 * Created by PhpStorm.
 * User: administrator
 * Date: 28/12/18
 * Time: 8:10 AM
 */

class EmployeeExpensesTypesListConfigurationFactory extends ohrmListConfigurationFactory
{


    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $header1 = new ListHeader();
        $header2 = new ListHeader();
        $header3 = new ListHeader();


        $header1->populateFromArray(array(

            'name' => __('Expense Name'),
            'isSortable' => true,
            'elementType' => 'label',
            'textAlignmentStyle' => 'left',
            'elementProperty' => array(
                'getter' => array('getName')
            )
        ));

        $header2->populateFromArray(array(

            'name' => __('Description'),
            'isSortable' => false,
            'elementType' => 'label',
            'textAlignmentStyle' => 'left',
            'elementProperty' => array(
                'getter' => array('getDescription')

            )
        ));
        $header3->populateFromArray(array(

            'name' => __('Status'),
            'isSortable' => false,
            'elementType' => 'label',
            'textAlignmentStyle' => 'left',
            'elementProperty' => array(
                'getter' => array('getStatus')

            )
        ));

        $this->headers = array($header1, $header2,$header3);
    }

    /**
     * @return string
     */
    public function getClassName()
    {
        // TODO: Implement getClassName() method.
        return 'ExpenseType';
    }


}