<?php
/**
 * Created by PhpStorm.
 * User: administrator
 * Date: 27/12/18
 * Time: 4:41 PM
 */

class CreateExpenseTypesForm extends sfForm

{

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub


        $this->setWidgets(array(
            'id' => new sfWidgetFormInputHidden(),
            'expenseName' => new sfWidgetFormInput(),
            'description' => new sfWidgetFormInput(),
            'status' => new sfWidgetFormChoice(array('expanded' => true, 'choices' => array('Active' => __("Active"), 'Inactive' => __("Inactive")))),
        ));
        $this->setValidators(array(
            'expenseName' => new sfValidatorString(array('required' => true, 'max_length' => 255)),
            'description' => new sfValidatorString(array('required' => false, 'max_length' => 1000)),
            'status' => new sfValidatorChoice(array('required' => true,
                'choices' => array('Active', 'Inactive'),
                'multiple' => false)),

        ));
        $this->widgetSchema->setLabels(array(
            'expenseName' => __('Event Name') . ' <em>*</em>',
            'description' => __('Description'),
            'status' => __('Status') . '<em>*</em>'
        ));
        $this->getWidgetSchema()->setNameFormat('createExpenses[%s]');

    }


}