<?php
/**
 * Created by PhpStorm.
 * User: administrator
 * Date: 26/12/18
 * Time: 5:01 PM
 */

class orangehrmClaimPluginConfiguration extends sfPluginConfiguration
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $enabledModules=sfConfig::get('sf_enabled_modules');
        if(is_array($enabledModules)){
            sfConfig::set('sf_enabled_modules',array_merge($enabledModules,array('claim')));
        }
    }
}


